-- ============================================================
-- 008b_durations_generated.sql  (one-off data fill, NOT a migration)
--
-- Generated by scripts/backfill-durations.mjs, which read each song's
-- audio header from R2 with a Range request. All 37 were readable.
-- Optional: durations only feed the 'duration' field of the MusicRecording
-- JSON-LD. Without them the structured data simply omits it.
--
-- Review, then run through the MCP or the Supabase SQL editor.
-- From 1A-5 the admin captures duration automatically on upload, so this
-- is only for the songs that predate that.
-- ============================================================
update public.songs set duration_seconds = 440 where id = '5647c338-0aee-4472-8e35-44dad08c5477';  -- אחת שאלתי
update public.songs set duration_seconds = 335 where id = 'abf4ba76-070d-43ec-8160-ecdfe957c482';  -- קרבת השם
update public.songs set duration_seconds = 414 where id = '12d66820-a844-4679-8220-4985e97c54cd';  -- Fires Still Burning
update public.songs set duration_seconds = 356 where id = '17431641-c8e1-4d6c-ae7a-8ea371a677e5';  -- Holy Land Vacation
update public.songs set duration_seconds = 480 where id = '79e6ae2f-db2b-406c-b031-bebae6bdb059';  -- Jewish USA
update public.songs set duration_seconds = 288 where id = '62c8b530-2456-4fa2-bf52-c797bfedea65';  -- My Perfect World
update public.songs set duration_seconds = 299 where id = 'c892909b-9a00-4e5e-bf52-bd3df6a89165';  -- Rising Like Lions
update public.songs set duration_seconds = 365 where id = '2cc83758-1e78-43a9-a459-fe7f676662ad';  -- Segulos Galore
update public.songs set duration_seconds = 324 where id = '9e712dfb-8fe4-416e-a181-c1a1e9c63112';  -- She Carried Me
update public.songs set duration_seconds = 305 where id = '9ed307f8-a5dd-455e-a598-488fa108abcf';  -- Standing Proud
update public.songs set duration_seconds = 372 where id = '87970626-1750-4b75-b120-8d604b2e6b0d';  -- The Walls Fall First
update public.songs set duration_seconds = 391 where id = '10a25793-5798-4a80-898d-446db4250787';  -- היום הרת עולם
update public.songs set duration_seconds = 331 where id = 'b8dd8c24-efc2-45e5-ac52-b11a3d1f9aa8';  -- Al Tashlicheini
update public.songs set duration_seconds = 299 where id = 'a3cae0ba-3e6b-459e-aec8-69df43d8a7e0';  -- Emet La'amito
update public.songs set duration_seconds = 262 where id = 'e93cf5c6-5e61-4fe7-9413-c6646438d48d';  -- ברכי נפשי
update public.songs set duration_seconds = 292 where id = 'f0e43564-e330-49ed-a69e-4767cbc8a323';  -- Geshem V'Tal
update public.songs set duration_seconds = 323 where id = '0d81a4bc-22ff-4bd9-8f24-1ab9340501c7';  -- Dovid's Holy Dance
update public.songs set duration_seconds = 292 where id = 'f3dab55d-20df-4aaa-b499-f9cc81596bef';  -- Do Your Best
update public.songs set duration_seconds = 367 where id = '5a5ded57-dcde-463a-90f8-22e170d7538f';  -- Shattered Exile
update public.songs set duration_seconds = 33 where id = '7886ccfc-85e0-40ae-8454-99230b364981';  -- Hear it From Them
update public.songs set duration_seconds = 301 where id = 'f1a18aad-35ee-4c86-b7fe-7a8bdb3a004a';  -- Shechina Returns
update public.songs set duration_seconds = 409 where id = '37340b42-e6db-42d9-a331-43ac45497385';  -- Touch My Soul
update public.songs set duration_seconds = 238 where id = 'c40b39c9-e4ab-4585-8b8a-d26dd0416094';  -- How I wish
update public.songs set duration_seconds = 266 where id = '0670f698-7866-45b5-bdbf-5f02fbb52192';  -- Mal'ah Ha'aretz Deah
update public.songs set duration_seconds = 400 where id = '13e9a1bf-19cf-4087-ba7c-6f77676718d7';  -- Yearnings
update public.songs set duration_seconds = 324 where id = 'f60c7275-f94f-4ba5-893f-ef73a05e0e4c';  -- Sulam Yaakov
update public.songs set duration_seconds = 281 where id = '2a3e1636-f169-4fc4-a89f-428939b43533';  -- Oseh Shalom
update public.songs set duration_seconds = 341 where id = '3a59fa48-8598-47f4-b86e-fa9367d534ff';  -- Al Blima
update public.songs set duration_seconds = 322 where id = '6fb0343d-db8e-4cd4-b3a2-08f4b8284eaf';  -- We can conquer!
update public.songs set duration_seconds = 312 where id = 'c6272ed4-8f13-4fa3-9715-34923d16ebb6';  -- Please Open
update public.songs set duration_seconds = 404 where id = 'b40bb288-cfce-4ae5-91ae-c217d796c3d9';  -- Kamu Vaneha
update public.songs set duration_seconds = 323 where id = 'a6d0d5fe-fda1-4cdd-94a8-66b7319ad2b3';  -- Rebirth
update public.songs set duration_seconds = 234 where id = '947dbe79-d564-4612-8afa-3750272402aa';  -- In a Flash
update public.songs set duration_seconds = 336 where id = 'f4b26177-1af6-4875-ae8f-726a7633db72';  -- Refaeinu
update public.songs set duration_seconds = 293 where id = '00d5043f-ce81-4170-866f-61ae8adf56b0';  -- Home for the Shechina
update public.songs set duration_seconds = 229 where id = '26b4bc4d-28a4-4858-ab2a-988a2c37bc87';  -- שמם אדם
update public.songs set duration_seconds = 334 where id = '7ee608a4-5082-48e6-bdfe-8f54135bc944';  -- Tiferet Banim
